# Generated by Django 2.1.5 on 2019-01-25 08:35

from django.db import migrations, models

def set_segment_size(apps, schema_editor):
    Task = apps.get_model('engine', 'Task')
    for task in Task.objects.all():
        segment = task.segment_set.first()
        task.segment_size = segment.stop_frame - segment.start_frame + 1
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_job_max_shape_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='segment_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(code=set_segment_size,
            reverse_code=migrations.RunPython.noop),

        migrations.AlterField(
            model_name='task',
            name='segment_size',
            field=models.PositiveIntegerField(),
        ),
    ]
